from __future__ import annotations

import os
import subprocess
import time
from pathlib import Path

import numpy as np
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine, text
from supabase import create_client

ROOT = Path(__file__).resolve().parents[1]
load_dotenv(str(ROOT / ".env"), override=True)

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")
TABLE_NAME = os.getenv("SUPABASE_TABLE", "wine_quality")
DATABASE_URL = (os.getenv("DATABASE_URL") or "").strip().strip('"').strip("'")
ALLOW_LOCAL_FALLBACK = os.getenv("ALLOW_LOCAL_FALLBACK", "false").lower() == "true"

DEFAULT_SOURCE = ROOT / "data" / "wine_quality.csv"
DEFAULT_RAW_OUT = ROOT / "data" / "raw" / "wine_quality.csv"
KAGGLE_RAW_PATH = ROOT / "data" / "raw" / "winequalityN.csv"
KAGGLE_DATASET = "rajyellow46/wine-quality"
KAGGLE_FILE = "winequalityN.csv"

BATCH_SIZE = 500


def _get_client():
    return create_client(SUPABASE_URL, SUPABASE_KEY)


RENAME_MAP = {
    "ph": "ph",
    "fixed_acidity": "fixed_acidity",
    # adicione aqui qualquer coluna com nome diferente
}


def _normalize_columns(df: pd.DataFrame) -> pd.DataFrame:
    df = df.rename(columns=lambda c: c.strip().replace(" ", "_").lower())
    return df.rename(columns=RENAME_MAP)


def _infer_pg_type(series: pd.Series) -> str:
    if pd.api.types.is_integer_dtype(series):
        return "integer"
    if pd.api.types.is_float_dtype(series):
        return "double precision"
    return "text"


def _ensure_table_exists_from_csv(csv_path: Path) -> None:
    """
    Cria a tabela no Supabase/Postgres automaticamente usando cabeçalho + tipos inferidos
    do CSV, se ela ainda não existir.
    """
    if not DATABASE_URL:
        raise RuntimeError(
            "DATABASE_URL não configurada; impossível criar tabela automaticamente."
        )

    print(f"[ingestion] Preparando schema da tabela a partir de: {csv_path}")
    df = _load_csv(csv_path)
    if df.empty:
        raise RuntimeError(f"CSV de seed vazio: {csv_path}")

    col_defs = []
    if "id" not in df.columns:
        col_defs.append('"id" bigint generated by default as identity primary key')

    for col in df.columns:
        pg_type = _infer_pg_type(df[col])
        col_defs.append(f'"{col}" {pg_type}')

    create_sql = (
        f'CREATE TABLE IF NOT EXISTS public."{TABLE_NAME}" (\n  '
        + ",\n  ".join(col_defs)
        + "\n);"
    )

    print(f"[ingestion] Conectando no Postgres para criar tabela '{TABLE_NAME}'...")
    engine = create_engine(
        DATABASE_URL,
        pool_pre_ping=True,
        connect_args={"connect_timeout": 15},
    )
    with engine.begin() as conn:
        conn.execute(text(create_sql))
    print(f"[ingestion] SQL CREATE TABLE executado com sucesso.")

    print(f"[ingestion] ✅ Tabela garantida/criada: public.{TABLE_NAME}")


def _load_csv(path: Path) -> pd.DataFrame:
    """Lê CSV com separador ';' (padrão UCI) ou ',' como fallback."""
    df = pd.read_csv(path, sep=";")
    if df.shape[1] == 1:
        df = pd.read_csv(path, sep=",")
    return _normalize_columns(df)


def _json_safe_records(df: pd.DataFrame) -> list[dict]:
    """
    Converte DataFrame para registros JSON-safe:
    - NaN/NaT -> None
    """
    safe_df = df.replace([np.inf, -np.inf], np.nan)
    safe_df = safe_df.astype(object).where(pd.notnull(safe_df), None)
    return safe_df.to_dict(orient="records")


def fetch_wine_data() -> pd.DataFrame:
    client = _get_client()

    # Debug: contar registros (falha aqui se tabela não existir)
    try:
        count_resp = client.table(TABLE_NAME).select("*", count="exact").limit(1).execute()
    except Exception as exc:
        msg = str(exc)
        if (
            "does not exist" in msg
            or "relation" in msg
            or "PGRST205" in msg
            or "schema cache" in msg
            or f"public.{TABLE_NAME}" in msg
        ):
            raise RuntimeError(
                f"Tabela '{TABLE_NAME}' não existe no Supabase. "
                "Crie a tabela antes da ingestão (schema com colunas do winequalityN.csv)."
            ) from exc
        raise RuntimeError(f"Falha ao consultar Supabase: {msg}") from exc

    print(f"[debug] Count exato: {count_resp.count}")
    print(f"[debug] Primeiros dados: {count_resp.data}")

    all_rows = []
    page = 0
    page_size = 1000

    while True:
        response = (
            client.table(TABLE_NAME)
            .select("*")
            .range(page * page_size, (page + 1) * page_size - 1)
            .execute()
        )
        batch = response.data
        if not batch:
            break
        all_rows.extend(batch)
        if len(batch) < page_size:
            break
        page += 1

    print(f"[ingestion] Total buscado: {len(all_rows)} linhas")
    return pd.DataFrame(all_rows)


def _download_kaggle_csv(
    dataset: str = KAGGLE_DATASET,
    filename: str = KAGGLE_FILE,
    out_dir: Path = KAGGLE_RAW_PATH.parent,
) -> Path:
    """
    Baixa CSV do Kaggle via CLI:
      kaggle datasets download -d <dataset> -f <file> -p <dir> --unzip
    Requer KAGGLE_USERNAME/KAGGLE_KEY ou ~/.kaggle/kaggle.json.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / filename

    cmd = [
        "kaggle",
        "datasets",
        "download",
        "-d",
        dataset,
        "-f",
        filename,
        "-p",
        str(out_dir),
        "--unzip",
    ]
    print(f"[ingestion] Baixando Kaggle dataset: {dataset} ({filename})")
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True)
    except FileNotFoundError as exc:
        raise RuntimeError(
            "Kaggle CLI não encontrada. Instale com `pip install kaggle` "
            "e configure KAGGLE_USERNAME/KAGGLE_KEY."
        ) from exc
    if proc.returncode != 0:
        raise RuntimeError(
            "Falha ao baixar do Kaggle. "
            "Verifique kaggle CLI e credenciais (KAGGLE_USERNAME/KAGGLE_KEY). "
            f"stderr: {proc.stderr.strip()}"
        )
    if not out_file.exists():
        raise FileNotFoundError(f"Arquivo esperado não encontrado após download: {out_file}")
    print(f"[ingestion] ✅ Kaggle CSV disponível em: {out_file}")
    return out_file


def _resolve_existing_local_seed(preferred: Path) -> Path:
    candidates = [
        preferred,
        ROOT / "data" / "raw" / "wine_quality.csv",
        ROOT / "data" / "winequalityN.csv",
        ROOT / "data" / "raw" / "winequalityN.csv",
    ]
    for p in candidates:
        if p.exists():
            print(f"[ingestion] Usando seed local: {p}")
            return p
    raise FileNotFoundError(
        "Nenhum CSV local de seed encontrado. "
        "Esperado em: data/wine_quality.csv, data/raw/wine_quality.csv ou data/raw/winequalityN.csv"
    )


def _resolve_seed_source(local_fallback: Path) -> Path:
    """Prioriza Kaggle CSV; em caso de erro usa fallback local existente."""
    try:
        return _download_kaggle_csv()
    except Exception as exc:
        print(f"[ingestion] ⚠️  Kaggle indisponível, usando fallback local: {exc}")
        return _resolve_existing_local_seed(local_fallback)


def _seed(source_csv: Path) -> None:
    print("[ingestion] Iniciando seed (upsert)…")
    df = _load_csv(source_csv)
    records = _json_safe_records(df)
    client = _get_client()

    for i in range(0, len(records), BATCH_SIZE):
        print(f"[ingestion] Upsert batch {i // BATCH_SIZE + 1}...")
        client.table(TABLE_NAME).insert(records[i : i + BATCH_SIZE]).execute()
        print(
            f"[ingestion] Seed: {min(i + BATCH_SIZE, len(records))}/{len(records)} linhas"
        )

    print(f"[ingestion] ✅ Seed completo — {len(records)} linhas em '{TABLE_NAME}'")


def _seed_via_sql(source_csv: Path) -> None:
    """
    Seed direto via SQL (Postgres), útil quando o PostgREST ainda não refletiu
    o schema cache da tabela recém-criada.
    """
    if not DATABASE_URL:
        raise RuntimeError("DATABASE_URL não configurada para seed via SQL.")

    print("[ingestion] Iniciando seed via SQL direto (sem REST)...")
    df = _load_csv(source_csv).replace([np.inf, -np.inf], np.nan)
    engine = create_engine(
        DATABASE_URL,
        pool_pre_ping=True,
        connect_args={"connect_timeout": 15},
    )
    with engine.begin() as conn:
        df.to_sql(
            TABLE_NAME,
            conn,
            schema="public",
            if_exists="append",
            index=False,
            chunksize=BATCH_SIZE,
            method="multi",
        )
    print(f"[ingestion] ✅ Seed SQL concluído — {len(df)} linhas em '{TABLE_NAME}'")


def ingest(source_csv: Path = DEFAULT_SOURCE, raw_out: Path = DEFAULT_RAW_OUT) -> None:
    raw_out.parent.mkdir(parents=True, exist_ok=True)

    try:
        print("[ingestion] Conectando via API REST (HTTPS)…")
        try:
            df = fetch_wine_data()
        except RuntimeError as exc:
            if "não existe" in str(exc):
                print("[ingestion] Tabela ausente no Supabase. Criando automaticamente…")
                seed_source = _resolve_seed_source(source_csv)
                _ensure_table_exists_from_csv(seed_source)
                _seed_via_sql(seed_source)
                # tenta buscar via REST; se cache ainda não atualizou, usa CSV local
                print("[ingestion] Aguardando refresh do schema cache (PostgREST)…")
                time.sleep(3)
                try:
                    df = fetch_wine_data()
                except Exception as cache_exc:
                    print(
                        "[ingestion] ⚠️  PostgREST ainda sem schema cache atualizado. "
                        f"Usando snapshot local temporariamente: {cache_exc}"
                    )
                    df = _load_csv(seed_source)
            else:
                raise

        # Tabela vazia → popular primeiro, depois buscar
        if df.empty:
            seed_source = _resolve_seed_source(source_csv)
            _seed(seed_source)
            df = fetch_wine_data()

        if df.empty:
            raise RuntimeError(
                "Seed executado mas tabela ainda vazia. Verifique o Supabase."
            )

        df = _normalize_columns(df)
        df.to_csv(raw_out, index=False)
        print(f"[ingestion] Shape: {df.shape}")
        print(f"[ingestion] ✅ Dados salvos em: {raw_out}")

    except Exception as e:
        if ALLOW_LOCAL_FALLBACK:
            print(f"[ingestion] ⚠️  Fallback local habilitado: {e}")
            df = _load_csv(source_csv)
            df.to_csv(raw_out, index=False)
            print(f"[ingestion] Dados salvos localmente em: {raw_out}")
        else:
            raise RuntimeError(
                f"[ingestion] Falha na ingestão via Supabase: {e}\n"
                "Defina ALLOW_LOCAL_FALLBACK=true no .env para permitir fallback local."
            ) from e


if __name__ == "__main__":
    ingest()
